version : '3'
services: # Services to deploy

  dockerapp1:
    image: dockerapp:1.0 #image name, Default:- Folder Name
    build:
      context: collect.calculator-api
      dockerfile: Dockerfile # path to dockerfile
    environment:
      RabbitMQSettings__ConnectionString: "amqp://admin:paszword@rabbitmq_hml"
    ports:
      - "3501:8080" # HOST_PORT:CONTAINER_PORT
    networks:
      - my-network

  dockerapp2:
    image: dockerapp:1.0 #image name, Default:- Folder Name
    ports:
      - "3502:8080" # HOST_PORT:CONTAINER_PORT
    networks:
      - my-network

  apigateway:
    image: apigateway:1.0
    build:
      context: collect.api-gateway
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
        - "8080:8080"
    networks:
      - my-network
  
  rabbitmq:
    image: rabbitmq:3.12.12-management
    container_name: rabbitmq_hml
    ports:
      - "5672:5672" # RabbitMQ server
      - "15672:15672" # RabbitMQ management console
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: paszword
    volumes:
       - ${RABBITMQ_DATA}:/var/lib/rabbitmq # Persist RabbitMQ data
    networks:
      - my-network
        
networks:
  my-network:
